### ISSUE TITLE
Add GitLab support

### ISSUE THREAD

**Issue by CameronBanga** [DoWhileGeek/open-repo#2] opened 2016-02-25 15:50 UTC
Tried the project out with GitLab. Looking at your code, the pattern seems like it should work, but getting "Could not parse remote url" when I attempt with a GitLab URL.

Any chance to add this?

**Comment by DoWhileGeek** [comment] 2016-02-25 21:33
I've never worked with gitlab before, I dont know what their uri's look like. If you can share the output of `git remote -v`, and the actual homepage of the remote, I'll add support.

**Comment by DoWhileGeek** [comment] 2018-02-27 16:43
Closing this as I cannot reproduce.

**Closed as completed by DoWhileGeek** 2018-02-27 16:43 UTC

**Comment by CameronBanga** [comment] 2018-02-27 17:02
I had forgotten all about this ticket and app, but just downloaded it and tested.

Can confirm, it works now!

**Comment by DoWhileGeek** [comment] 2018-02-27 17:04
🙌
